# Generated by Django 3.1.7 on 2021-04-01 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0002_auto_20210327_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_subject', models.CharField(max_length=100)),
                ('task_detail', models.TextField()),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task_Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(blank=True, null=True, upload_to='task_media/')),
                ('description', models.CharField(max_length=400)),
                ('media_mode', models.CharField(choices=[('assign', 'assign'), ('reply', 'reply')], default='assign', max_length=50)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.task')),
            ],
        ),
    ]
