# Generated by Django 3.1.7 on 2021-04-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20210401_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
