# Generated by Django 3.1.7 on 2021-04-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_notifications_take_leave_user_leave_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='end_lunch_break',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lunch_break_duration',
            field=models.CharField(blank=True, default='00:00:00 Hr', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='start_lunch_break',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
