# Generated by Django 3.1.7 on 2021-04-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_task_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='hr_attendance',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
    ]
