# Generated by Django 3.1.7 on 2021-05-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20210416_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Commitment',
            field=models.BooleanField(default=False),
        ),
    ]
