# Generated by Django 3.1.7 on 2021-04-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20210408_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hr_attendance',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
