# Generated by Django 3.1.7 on 2021-04-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20210408_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='duration',
            field=models.DurationField(blank=True, default='00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='hr_attendance',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
